---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitlab.credential.name }}
{{- with .Values.gitlab.credential.annotations }}
  annotations:
{{ toYaml . | indent 4 -}}
{{- end }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ include "base-pipelines.gitlabCredential.id_rsa" . | b64enc }}
  known_hosts: {{ include "base-pipelines.gitlabCredential.known_hosts" . | b64enc}}
---
